// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLwMvrhwOES1_PiZEvLI-PSzSgx-51dM',
    appId: '1:502755674100:web:b62c817c00a9aa34be9ba1',
    messagingSenderId: '502755674100',
    projectId: 'deep-focus-a8be2',
    authDomain: 'deep-focus-a8be2.firebaseapp.com',
    storageBucket: 'deep-focus-a8be2.firebasestorage.app',
    measurementId: 'G-C17T2S5HTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg9GFyN6jX3ftMLjE8v6GMQaxR3t758BM',
    appId: '1:502755674100:android:6230782949006818be9ba1',
    messagingSenderId: '502755674100',
    projectId: 'deep-focus-a8be2',
    storageBucket: 'deep-focus-a8be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt0Wp3l79xBxNTK4ZTjcv9kAI8GJpVjos',
    appId: '1:502755674100:ios:2cb47cc72db0b6a0be9ba1',
    messagingSenderId: '502755674100',
    projectId: 'deep-focus-a8be2',
    storageBucket: 'deep-focus-a8be2.firebasestorage.app',
    iosBundleId: 'com.example.appFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt0Wp3l79xBxNTK4ZTjcv9kAI8GJpVjos',
    appId: '1:502755674100:ios:2cb47cc72db0b6a0be9ba1',
    messagingSenderId: '502755674100',
    projectId: 'deep-focus-a8be2',
    storageBucket: 'deep-focus-a8be2.firebasestorage.app',
    iosBundleId: 'com.example.appFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLwMvrhwOES1_PiZEvLI-PSzSgx-51dM',
    appId: '1:502755674100:web:9814e84869fb6720be9ba1',
    messagingSenderId: '502755674100',
    projectId: 'deep-focus-a8be2',
    authDomain: 'deep-focus-a8be2.firebaseapp.com',
    storageBucket: 'deep-focus-a8be2.firebasestorage.app',
    measurementId: 'G-0S272Q24MD',
  );
}
